spring:
  datasource:
    url: jdbc:mysql://localhost/farmfoods
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialecta
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    enabled: false

  security:
    basic:
      enabled=false:
    user:
      name: user
      password: mmmm


  flyway:
    enabled: true
    url: jdbc:mysql://localhost
    user: root
    password: root
    schemas: farmfoods
  quartz:
    auto-startup: false
server:
  port: 9090
  servlet:
    context-path: /farmfoods
  error:
    include-message: always
