//pipeline {
//    agent any {
//        stages {
//            stage('build') {
//                steps {
//                    sh 'echo $JAVA_HOME'
//                    sh 'mvn --version'
//                    sh 'mvn clean compile war:war'
//                }
//            }
//        }
//    }
//}
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building.......'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }

}