pipeline {
    agent any {
        stages {
            stage('build') {
                steps {
                    sh 'echo $JAVA_HOME'
                    sh 'mvn --version'
                    sh 'mvn clean compile war:war'
                }
            }
        }
    }
}